<a href="https://colab.research.google.com/github/Darachhat/Pytorch-Intro/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Tensors

In [ ]:
import torch
import numpy as np

# Lists

In [ ]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# Numpy Arrays

In [ ]:
np1 = np.random.rand(3,4)
np1

array([[0.19843144, 0.76404735, 0.20274888, 0.48989126],
       [0.82365855, 0.71907548, 0.05327956, 0.70777056],
       [0.66935729, 0.56453059, 0.10781264, 0.62321724]])

In [ ]:
np1.dtype

dtype('float64')

# TENSORS


In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d
#tensor_2d.dtype

tensor([[ 1.1714,  0.6599,  1.2301, -0.0562],
        [-0.1031, -0.0995,  0.4045, -0.2489],
        [ 1.1801, -1.0572, -0.3667,  0.2712]])

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
## create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1984, 0.7640, 0.2027, 0.4899],
        [0.8237, 0.7191, 0.0533, 0.7078],
        [0.6694, 0.5645, 0.1078, 0.6232]], dtype=torch.float64)